---
- name: Checkout repository
  git:
    repo: "{{repositoryUrl}}"
    version: "{{branch}}"
    dest: "~/{{checkoutFolderName}}"

- name: Build Docker Image
  docker_image:
     path: "~/{{checkoutFolderName}}"
     name: "{{containerName}}"

- name: Run Docker Container
  docker_container:
    name: "{{containerName}}"
    image: "{{containerName}}"
    ports: "{{ports | default([])}}"
    exposed_ports: "{{exposedPorts | default([])}}"
    networks: "{{networks | default([])}}"
    purge_networks: yes
    state: started
    restart: yes

- name: Delete temporary checkout directory
  file:
    state: absent
    path: "~/{{checkoutFolderName}}"
