# This file should be located at <your-repository>/.deployer.yml

# (Required)
# The list of hosts where your project should be deployed to.
targetHosts:
    - worker-1.leventebalogh.com
    - worker-2.leventebalogh.com

# (Optional)
# The name of the docker container that will be started from the image.
# Deafults back to the name of the repository.
containerName: foo

# (Optional)
# The list of networks which should be attached to the container.
networks:
    - nginx
    - db

# (Optional)
# The list of ports you would like to expose from the container. 
ports:
    - 8080:8080
    - 8081:8081
